### ISSUE TITLE
Test Issues - "Could not initialize class org.apache.spark.rdd.RDDOperationScope"

### ISSUE THREAD

**Issue by dyno** [dyno/facets-overview-spark#2]
gradle test

```
20/03/05 11:19:19 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/Users/dynofu/gitroot/facets-overview-spark/spark-warehouse/').
20/03/05 11:19:19 INFO SharedState: Warehouse path is 'file:/Users/dynofu/gitroot/facets-overview-spark/spark-warehouse/'.
20/03/05 11:19:19 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
TensorStatsGeneratorTest:
*** RUN ABORTED *** (3 seconds, 997 milliseconds)
  java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at org.scalatest.tools.ConcurrentDistributor.waitUntilDone(ConcurrentDistributor.scala:50)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1305)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:972)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  ...
  Cause: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:296)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2836)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2835)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  ...

> Task :test FAILED
```

**Comment by dynofu** [comment]
```
20/03/07 11:17:40 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
FeatureStatsGeneratorTest:
*** RUN ABORTED *** (3 seconds, 647 milliseconds)
  java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at org.scalatest.tools.ConcurrentDistributor.waitUntilDone(ConcurrentDistributor.scala:50)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1305)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:972)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  ...
  Cause: java.lang.ExceptionInInitializerError:
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:296)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2836)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2835)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  ...
  Cause: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.9.8
  at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
  at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
  at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:751)
  at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
  at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:296)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2836)
  ...

> Task :test FAILED
```
so it is related to jackson https://stackoverflow.com/questions/31909368/spark-error-could-not-initialize-class-org-apache-spark-rdd-rddoperationscope

**Comment by dynofu** [comment]
```
+ cs resolve org.apache.spark:spark-sql_2.11:2.4.5
com.fasterxml.jackson.core:jackson-annotations:2.6.7:default
com.fasterxml.jackson.core:jackson-core:2.7.9:default
com.fasterxml.jackson.core:jackson-databind:2.6.7.3:default
com.fasterxml.jackson.module:jackson-module-paranamer:2.7.9:default
com.fasterxml.jackson.module:jackson-module-scala_2.11:2.6.7.1:default
org.apache.parquet:parquet-jackson:1.10.1:default
org.codehaus.jackson:jackson-core-asl:1.9.13:default
org.codehaus.jackson:jackson-jaxrs:1.9.13:default
org.codehaus.jackson:jackson-mapper-asl:1.9.13:default
org.codehaus.jackson:jackson-xc:1.9.13:default
org.json4s:json4s-jackson_2.11:3.5.3:default

+ cs resolve com.thesamet.scalapb:scalapb-json4s_2.11:0.10.0
com.fasterxml.jackson.core:jackson-annotations:2.9.0:default
com.fasterxml.jackson.core:jackson-core:2.9.8:default
com.fasterxml.jackson.core:jackson-databind:2.9.8:default
org.json4s:json4s-jackson_2.11:3.6.7:default
```

**Comment by dynofu** [comment]
https://stackoverflow.com/questions/31909368/spark-error-could-not-initialize-class-org-apache-spark-rdd-rddoperationscope/60582742#60582742
